# Generated by Django 4.1.3 on 2022-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Colour', models.CharField(max_length=200)),
                ('Size', models.IntegerField()),
            ],
        ),
    ]
