# Generated by Django 4.1.3 on 2022-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalsDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='Size',
            field=models.IntegerField(db_column='Size'),
        ),
    ]
