# Generated by Django 4.1.3 on 2022-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalsDemo', '0002_alter_animals_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='Size',
            field=models.IntegerField(),
        ),
    ]
